name: Deploy User System

on:
  push:
    branches: [main]
    paths:
      - 'backendcloud/usersystem/**'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

  publish:
    name: Package And Publish
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Build with Maven
        run: |
          cd backendcloud/usersystem
          mvn package
      
      - name: Login Docker
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: VenusHui/Fander-usersystem

      - name: Publish Docker Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: backendcloud/usersystem/Dockerfile
  
  deploy:
    name: Deployment
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy On Tencent Cloud Server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}
          script: cd ~/Fander/backendcloud/usersystem/ && bash deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} >> ./deploy.log